### ISSUE TITLE
Volumio 3.175 issue

### ISSUE THREAD

**Issue by MikkelLau** [dhrone/pydPiper#129]
Hi dhrone

I am having issues with the display only showing the artist playback som time. 

The clock works great and pydPiper always starts but I am only seeing the playback info every other or third time it boot up volumio. Some times a reboot helps, other times a start/stop in terminal helps.

This is the errors displayed running show updates:

`pydPiper starting
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/pydPiper.py", line 421, in updateconditions
    if self.checkaccuweatherreturn(r.status_code):
  File "/app/pydPiper.py", line 338, in checkaccuweatherreturn
    logging.warning('An unexpected return value was provide.  Value was [{0}]. Request was [{1}]'.format(status_code,querystr))
NameError: global name 'querystr' is not defined
`

Not quite sure what that means and if it is related to the missing playback info. Playback info is displayed at http://volumio.local/dev. Have tried running the install again and then disable the weather, but did not help...

Regards

**Comment by dhrone** [comment]
Looks like a bug in the accuweather code that is only triggered if accuweather returns certain types of error codes.  Short-term you could remove accuweather from your config and retry to see if that resolves the issue.
