### ISSUE TITLE
Error with latest version of Volumio

### ISSUE THREAD

**Issue by MichaelSwag** [dhrone/pydPiper#65]
root@werkplaats:/home/volumio/pydPiper# python /home/volumio/pydPiper/pydPiper.py --driver hd44780 --width 20 --height 4 --rs 7 --e 8 --d4 25 --d5 24 --d6 23 --d7 18 --pages pages_lcd_20x4.py

Loading font from /home/volumio/pydPiper/displays/fonts/latin1_5x8_fixed.fnt
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/volumio/pydPiper/pydPiper.py", line 735, in <module>
    mc = music_controller(services_list, dc, showupdates)
  File "/home/volumio/pydPiper/pydPiper.py", line 96, in __init__
    self.initservices()
  File "/home/volumio/pydPiper/pydPiper.py", line 125, in initservices
    musicservice = sources.musicdata_volumio2.musicdata_volumio2(self.musicqueue, pydPiper_config.VOLUMIO_SERVER, pydPiper_config.VOLUMIO_PORT, exitapp )
AttributeError: 'module' object has no attribute 'musicdata_volumio2'
Uncaught exception
Traceback (most recent call last):
  File "/home/volumio/pydPiper/pydPiper.py", line 735, in <module>
    mc = music_controller(services_list, dc, showupdates)
  File "/home/volumio/pydPiper/pydPiper.py", line 96, in __init__
    self.initservices()
  File "/home/volumio/pydPiper/pydPiper.py", line 125, in initservices
    musicservice = sources.musicdata_volumio2.musicdata_volumio2(self.musicqueue, pydPiper_config.VOLUMIO_SERVER, pydPiper_config.VOLUMIO_PORT, exitapp )
AttributeError: 'module' object has no attribute 'musicdata_volumio2'
Traceback (most recent call last):
  File "/home/volumio/pydPiper/pydPiper.py", line 735, in <module>
    mc = music_controller(services_list, dc, showupdates)
  File "/home/volumio/pydPiper/pydPiper.py", line 96, in __init__
    self.initservices()
  File "/home/volumio/pydPiper/pydPiper.py", line 125, in initservices
    musicservice = sources.musicdata_volumio2.musicdata_volumio2(self.musicqueue, pydPiper_config.VOLUMIO_SERVER, pydPiper_config.VOLUMIO_PORT, exitapp )
AttributeError: 'module' object has no attribute 'musicdata_volumio2'

**Comment by dhrone** [comment]
It looks like the musicdata_volumio2 module is not successfully loading.  What is the version of Volumio2 that you are using?
